<?php
declare(strict_types=1);

// ISO names are derived from i18n-iso-countries 7.14.0; calling metadata is
// derived from intl-tel-input 29.2.3. See THIRD_PARTY_NOTICES.md.
function fb_country_catalog(): array {
    static $countries = null;
    if ($countries !== null) return $countries;
    return $countries = [
        'AF' => ['name'=>'Afghanistan','dial'=>'93','prefix'=>'0'],
        'AL' => ['name'=>'Albania','dial'=>'355','prefix'=>'0'],
        'DZ' => ['name'=>'Algeria','dial'=>'213','prefix'=>'0'],
        'AS' => ['name'=>'American Samoa','dial'=>'1','prefix'=>'1'],
        'AD' => ['name'=>'Andorra','dial'=>'376','prefix'=>''],
        'AO' => ['name'=>'Angola','dial'=>'244','prefix'=>''],
        'AI' => ['name'=>'Anguilla','dial'=>'1','prefix'=>'1'],
        'AQ' => ['name'=>'Antarctica','dial'=>'','prefix'=>''],
        'AG' => ['name'=>'Antigua and Barbuda','dial'=>'1','prefix'=>'1'],
        'AR' => ['name'=>'Argentina','dial'=>'54','prefix'=>'0'],
        'AM' => ['name'=>'Armenia','dial'=>'374','prefix'=>'0'],
        'AW' => ['name'=>'Aruba','dial'=>'297','prefix'=>''],
        'AU' => ['name'=>'Australia','dial'=>'61','prefix'=>'0'],
        'AT' => ['name'=>'Austria','dial'=>'43','prefix'=>'0'],
        'AZ' => ['name'=>'Azerbaijan','dial'=>'994','prefix'=>'0'],
        'BS' => ['name'=>'Bahamas','dial'=>'1','prefix'=>'1'],
        'BH' => ['name'=>'Bahrain','dial'=>'973','prefix'=>''],
        'BD' => ['name'=>'Bangladesh','dial'=>'880','prefix'=>'0'],
        'BB' => ['name'=>'Barbados','dial'=>'1','prefix'=>'1'],
        'BY' => ['name'=>'Belarus','dial'=>'375','prefix'=>'8'],
        'BE' => ['name'=>'Belgium','dial'=>'32','prefix'=>'0'],
        'BZ' => ['name'=>'Belize','dial'=>'501','prefix'=>''],
        'BJ' => ['name'=>'Benin','dial'=>'229','prefix'=>''],
        'BM' => ['name'=>'Bermuda','dial'=>'1','prefix'=>'1'],
        'BT' => ['name'=>'Bhutan','dial'=>'975','prefix'=>''],
        'BO' => ['name'=>'Bolivia','dial'=>'591','prefix'=>'0'],
        'BA' => ['name'=>'Bosnia and Herzegovina','dial'=>'387','prefix'=>'0'],
        'BW' => ['name'=>'Botswana','dial'=>'267','prefix'=>''],
        'BV' => ['name'=>'Bouvet Island','dial'=>'','prefix'=>''],
        'BR' => ['name'=>'Brazil','dial'=>'55','prefix'=>'0'],
        'IO' => ['name'=>'British Indian Ocean Territory','dial'=>'246','prefix'=>''],
        'BN' => ['name'=>'Brunei Darussalam','dial'=>'673','prefix'=>''],
        'BG' => ['name'=>'Bulgaria','dial'=>'359','prefix'=>'0'],
        'BF' => ['name'=>'Burkina Faso','dial'=>'226','prefix'=>''],
        'BI' => ['name'=>'Burundi','dial'=>'257','prefix'=>''],
        'KH' => ['name'=>'Cambodia','dial'=>'855','prefix'=>'0'],
        'CM' => ['name'=>'Cameroon','dial'=>'237','prefix'=>''],
        'CA' => ['name'=>'Canada','dial'=>'1','prefix'=>'1'],
        'CV' => ['name'=>'Cape Verde','dial'=>'238','prefix'=>''],
        'KY' => ['name'=>'Cayman Islands','dial'=>'1','prefix'=>'1'],
        'CF' => ['name'=>'Central African Republic','dial'=>'236','prefix'=>''],
        'TD' => ['name'=>'Chad','dial'=>'235','prefix'=>''],
        'CL' => ['name'=>'Chile','dial'=>'56','prefix'=>''],
        'CN' => ['name'=>'China','dial'=>'86','prefix'=>'0'],
        'CX' => ['name'=>'Christmas Island','dial'=>'61','prefix'=>'0'],
        'CC' => ['name'=>'Cocos (Keeling) Islands','dial'=>'61','prefix'=>'0'],
        'CO' => ['name'=>'Colombia','dial'=>'57','prefix'=>'0'],
        'KM' => ['name'=>'Comoros','dial'=>'269','prefix'=>''],
        'CG' => ['name'=>'Congo','dial'=>'242','prefix'=>''],
        'CD' => ['name'=>'Congo','dial'=>'243','prefix'=>'0'],
        'CK' => ['name'=>'Cook Islands','dial'=>'682','prefix'=>''],
        'CR' => ['name'=>'Costa Rica','dial'=>'506','prefix'=>''],
        'CI' => ['name'=>'Ivory Coast','dial'=>'225','prefix'=>''],
        'HR' => ['name'=>'Croatia','dial'=>'385','prefix'=>'0'],
        'CU' => ['name'=>'Cuba','dial'=>'53','prefix'=>'0'],
        'CY' => ['name'=>'Cyprus','dial'=>'357','prefix'=>''],
        'CZ' => ['name'=>'Czechia','dial'=>'420','prefix'=>''],
        'DK' => ['name'=>'Denmark','dial'=>'45','prefix'=>''],
        'DJ' => ['name'=>'Djibouti','dial'=>'253','prefix'=>''],
        'DM' => ['name'=>'Dominica','dial'=>'1','prefix'=>'1'],
        'DO' => ['name'=>'Dominican Republic','dial'=>'1','prefix'=>'1'],
        'EC' => ['name'=>'Ecuador','dial'=>'593','prefix'=>'0'],
        'EG' => ['name'=>'Egypt','dial'=>'20','prefix'=>'0'],
        'SV' => ['name'=>'El Salvador','dial'=>'503','prefix'=>''],
        'GQ' => ['name'=>'Equatorial Guinea','dial'=>'240','prefix'=>''],
        'ER' => ['name'=>'Eritrea','dial'=>'291','prefix'=>'0'],
        'EE' => ['name'=>'Estonia','dial'=>'372','prefix'=>''],
        'ET' => ['name'=>'Ethiopia','dial'=>'251','prefix'=>'0'],
        'FK' => ['name'=>'Falkland Islands (Malvinas)','dial'=>'500','prefix'=>''],
        'FO' => ['name'=>'Faroe Islands','dial'=>'298','prefix'=>''],
        'FJ' => ['name'=>'Fiji','dial'=>'679','prefix'=>''],
        'FI' => ['name'=>'Finland','dial'=>'358','prefix'=>'0'],
        'FR' => ['name'=>'France','dial'=>'33','prefix'=>'0'],
        'GF' => ['name'=>'French Guiana','dial'=>'594','prefix'=>'0'],
        'PF' => ['name'=>'French Polynesia','dial'=>'689','prefix'=>''],
        'TF' => ['name'=>'French Southern Territories','dial'=>'','prefix'=>''],
        'GA' => ['name'=>'Gabon','dial'=>'241','prefix'=>''],
        'GM' => ['name'=>'Gambia','dial'=>'220','prefix'=>''],
        'GE' => ['name'=>'Georgia','dial'=>'995','prefix'=>'0'],
        'DE' => ['name'=>'Germany','dial'=>'49','prefix'=>'0'],
        'GH' => ['name'=>'Ghana','dial'=>'233','prefix'=>'0'],
        'GI' => ['name'=>'Gibraltar','dial'=>'350','prefix'=>''],
        'GR' => ['name'=>'Greece','dial'=>'30','prefix'=>''],
        'GL' => ['name'=>'Greenland','dial'=>'299','prefix'=>''],
        'GD' => ['name'=>'Grenada','dial'=>'1','prefix'=>'1'],
        'GP' => ['name'=>'Guadeloupe','dial'=>'590','prefix'=>'0'],
        'GU' => ['name'=>'Guam','dial'=>'1','prefix'=>'1'],
        'GT' => ['name'=>'Guatemala','dial'=>'502','prefix'=>''],
        'GN' => ['name'=>'Guinea','dial'=>'224','prefix'=>''],
        'GW' => ['name'=>'Guinea-Bissau','dial'=>'245','prefix'=>''],
        'GY' => ['name'=>'Guyana','dial'=>'592','prefix'=>''],
        'HT' => ['name'=>'Haiti','dial'=>'509','prefix'=>''],
        'HM' => ['name'=>'Heard Island and McDonald Islands','dial'=>'','prefix'=>''],
        'VA' => ['name'=>'Holy See (Vatican City State)','dial'=>'39','prefix'=>''],
        'HN' => ['name'=>'Honduras','dial'=>'504','prefix'=>''],
        'HK' => ['name'=>'Hong Kong','dial'=>'852','prefix'=>''],
        'HU' => ['name'=>'Hungary','dial'=>'36','prefix'=>'06'],
        'IS' => ['name'=>'Iceland','dial'=>'354','prefix'=>''],
        'IN' => ['name'=>'India','dial'=>'91','prefix'=>'0'],
        'ID' => ['name'=>'Indonesia','dial'=>'62','prefix'=>'0'],
        'IR' => ['name'=>'Iran','dial'=>'98','prefix'=>'0'],
        'IQ' => ['name'=>'Iraq','dial'=>'964','prefix'=>'0'],
        'IE' => ['name'=>'Ireland','dial'=>'353','prefix'=>'0'],
        'IL' => ['name'=>'Israel','dial'=>'972','prefix'=>'0'],
        'IT' => ['name'=>'Italy','dial'=>'39','prefix'=>''],
        'JM' => ['name'=>'Jamaica','dial'=>'1','prefix'=>'1'],
        'JP' => ['name'=>'Japan','dial'=>'81','prefix'=>'0'],
        'JO' => ['name'=>'Jordan','dial'=>'962','prefix'=>'0'],
        'KZ' => ['name'=>'Kazakhstan','dial'=>'7','prefix'=>'8'],
        'KE' => ['name'=>'Kenya','dial'=>'254','prefix'=>'0'],
        'KI' => ['name'=>'Kiribati','dial'=>'686','prefix'=>'0'],
        'KP' => ['name'=>'North Korea','dial'=>'850','prefix'=>'0'],
        'KR' => ['name'=>'Republic of Korea','dial'=>'82','prefix'=>'0'],
        'KW' => ['name'=>'Kuwait','dial'=>'965','prefix'=>''],
        'KG' => ['name'=>'Kyrgyzstan','dial'=>'996','prefix'=>'0'],
        'LA' => ['name'=>'Lao People\'s Democratic Republic','dial'=>'856','prefix'=>'0'],
        'LV' => ['name'=>'Latvia','dial'=>'371','prefix'=>''],
        'LB' => ['name'=>'Lebanon','dial'=>'961','prefix'=>'0'],
        'LS' => ['name'=>'Lesotho','dial'=>'266','prefix'=>''],
        'LR' => ['name'=>'Liberia','dial'=>'231','prefix'=>'0'],
        'LY' => ['name'=>'Libya','dial'=>'218','prefix'=>'0'],
        'LI' => ['name'=>'Liechtenstein','dial'=>'423','prefix'=>'0'],
        'LT' => ['name'=>'Lithuania','dial'=>'370','prefix'=>'0'],
        'LU' => ['name'=>'Luxembourg','dial'=>'352','prefix'=>''],
        'MO' => ['name'=>'Macao','dial'=>'853','prefix'=>''],
        'MG' => ['name'=>'Madagascar','dial'=>'261','prefix'=>'0'],
        'MW' => ['name'=>'Malawi','dial'=>'265','prefix'=>'0'],
        'MY' => ['name'=>'Malaysia','dial'=>'60','prefix'=>'0'],
        'MV' => ['name'=>'Maldives','dial'=>'960','prefix'=>''],
        'ML' => ['name'=>'Mali','dial'=>'223','prefix'=>''],
        'MT' => ['name'=>'Malta','dial'=>'356','prefix'=>''],
        'MH' => ['name'=>'Marshall Islands','dial'=>'692','prefix'=>'1'],
        'MQ' => ['name'=>'Martinique','dial'=>'596','prefix'=>'0'],
        'MR' => ['name'=>'Mauritania','dial'=>'222','prefix'=>''],
        'MU' => ['name'=>'Mauritius','dial'=>'230','prefix'=>''],
        'YT' => ['name'=>'Mayotte','dial'=>'262','prefix'=>'0'],
        'MX' => ['name'=>'Mexico','dial'=>'52','prefix'=>''],
        'FM' => ['name'=>'Micronesia, Federated States of','dial'=>'691','prefix'=>''],
        'MD' => ['name'=>'Moldova, Republic of','dial'=>'373','prefix'=>'0'],
        'MC' => ['name'=>'Monaco','dial'=>'377','prefix'=>'0'],
        'MN' => ['name'=>'Mongolia','dial'=>'976','prefix'=>'0'],
        'MS' => ['name'=>'Montserrat','dial'=>'1','prefix'=>'1'],
        'MA' => ['name'=>'Morocco','dial'=>'212','prefix'=>'0'],
        'MZ' => ['name'=>'Mozambique','dial'=>'258','prefix'=>''],
        'MM' => ['name'=>'Myanmar','dial'=>'95','prefix'=>'0'],
        'NA' => ['name'=>'Namibia','dial'=>'264','prefix'=>'0'],
        'NR' => ['name'=>'Nauru','dial'=>'674','prefix'=>''],
        'NP' => ['name'=>'Nepal','dial'=>'977','prefix'=>'0'],
        'NL' => ['name'=>'Netherlands (Kingdom of the)','dial'=>'31','prefix'=>'0'],
        'NC' => ['name'=>'New Caledonia','dial'=>'687','prefix'=>''],
        'NZ' => ['name'=>'New Zealand','dial'=>'64','prefix'=>'0'],
        'NI' => ['name'=>'Nicaragua','dial'=>'505','prefix'=>''],
        'NE' => ['name'=>'Niger','dial'=>'227','prefix'=>''],
        'NG' => ['name'=>'Nigeria','dial'=>'234','prefix'=>'0'],
        'NU' => ['name'=>'Niue','dial'=>'683','prefix'=>''],
        'NF' => ['name'=>'Norfolk Island','dial'=>'672','prefix'=>''],
        'MP' => ['name'=>'Northern Mariana Islands','dial'=>'1','prefix'=>'1'],
        'MK' => ['name'=>'North Macedonia','dial'=>'389','prefix'=>'0'],
        'NO' => ['name'=>'Norway','dial'=>'47','prefix'=>''],
        'OM' => ['name'=>'Oman','dial'=>'968','prefix'=>''],
        'PK' => ['name'=>'Pakistan','dial'=>'92','prefix'=>'0'],
        'PW' => ['name'=>'Palau','dial'=>'680','prefix'=>''],
        'PS' => ['name'=>'Palestine','dial'=>'970','prefix'=>'0'],
        'PA' => ['name'=>'Panama','dial'=>'507','prefix'=>''],
        'PG' => ['name'=>'Papua New Guinea','dial'=>'675','prefix'=>''],
        'PY' => ['name'=>'Paraguay','dial'=>'595','prefix'=>'0'],
        'PE' => ['name'=>'Peru','dial'=>'51','prefix'=>'0'],
        'PH' => ['name'=>'Philippines','dial'=>'63','prefix'=>'0'],
        'PN' => ['name'=>'Pitcairn Islands','dial'=>'','prefix'=>''],
        'PL' => ['name'=>'Poland','dial'=>'48','prefix'=>''],
        'PT' => ['name'=>'Portugal','dial'=>'351','prefix'=>''],
        'PR' => ['name'=>'Puerto Rico','dial'=>'1','prefix'=>'1'],
        'QA' => ['name'=>'Qatar','dial'=>'974','prefix'=>''],
        'RE' => ['name'=>'Reunion','dial'=>'262','prefix'=>'0'],
        'RO' => ['name'=>'Romania','dial'=>'40','prefix'=>'0'],
        'RU' => ['name'=>'Russia','dial'=>'7','prefix'=>'8'],
        'RW' => ['name'=>'Rwanda','dial'=>'250','prefix'=>'0'],
        'SH' => ['name'=>'Saint Helena','dial'=>'290','prefix'=>''],
        'KN' => ['name'=>'Saint Kitts and Nevis','dial'=>'1','prefix'=>'1'],
        'LC' => ['name'=>'Saint Lucia','dial'=>'1','prefix'=>'1'],
        'PM' => ['name'=>'Saint Pierre and Miquelon','dial'=>'508','prefix'=>'0'],
        'VC' => ['name'=>'Saint Vincent and the Grenadines','dial'=>'1','prefix'=>'1'],
        'WS' => ['name'=>'Samoa','dial'=>'685','prefix'=>''],
        'SM' => ['name'=>'San Marino','dial'=>'378','prefix'=>''],
        'ST' => ['name'=>'Sao Tome and Principe','dial'=>'239','prefix'=>''],
        'SA' => ['name'=>'Saudi Arabia','dial'=>'966','prefix'=>'0'],
        'SN' => ['name'=>'Senegal','dial'=>'221','prefix'=>''],
        'SC' => ['name'=>'Seychelles','dial'=>'248','prefix'=>''],
        'SL' => ['name'=>'Sierra Leone','dial'=>'232','prefix'=>'0'],
        'SG' => ['name'=>'Singapore','dial'=>'65','prefix'=>''],
        'SK' => ['name'=>'Slovakia','dial'=>'421','prefix'=>'0'],
        'SI' => ['name'=>'Slovenia','dial'=>'386','prefix'=>'0'],
        'SB' => ['name'=>'Solomon Islands','dial'=>'677','prefix'=>''],
        'SO' => ['name'=>'Somalia','dial'=>'252','prefix'=>'0'],
        'ZA' => ['name'=>'South Africa','dial'=>'27','prefix'=>'0'],
        'GS' => ['name'=>'South Georgia and the South Sandwich Islands','dial'=>'','prefix'=>''],
        'ES' => ['name'=>'Spain','dial'=>'34','prefix'=>''],
        'LK' => ['name'=>'Sri Lanka','dial'=>'94','prefix'=>'0'],
        'SD' => ['name'=>'Sudan','dial'=>'249','prefix'=>'0'],
        'SR' => ['name'=>'Suriname','dial'=>'597','prefix'=>''],
        'SJ' => ['name'=>'Svalbard and Jan Mayen','dial'=>'47','prefix'=>''],
        'SZ' => ['name'=>'Eswatini','dial'=>'268','prefix'=>''],
        'SE' => ['name'=>'Sweden','dial'=>'46','prefix'=>'0'],
        'CH' => ['name'=>'Switzerland','dial'=>'41','prefix'=>'0'],
        'SY' => ['name'=>'Syrian Arab Republic','dial'=>'963','prefix'=>'0'],
        'TW' => ['name'=>'Taiwan','dial'=>'886','prefix'=>'0'],
        'TJ' => ['name'=>'Tajikistan','dial'=>'992','prefix'=>''],
        'TZ' => ['name'=>'Tanzania','dial'=>'255','prefix'=>'0'],
        'TH' => ['name'=>'Thailand','dial'=>'66','prefix'=>'0'],
        'TL' => ['name'=>'Timor-Leste','dial'=>'670','prefix'=>''],
        'TG' => ['name'=>'Togo','dial'=>'228','prefix'=>''],
        'TK' => ['name'=>'Tokelau','dial'=>'690','prefix'=>''],
        'TO' => ['name'=>'Tonga','dial'=>'676','prefix'=>''],
        'TT' => ['name'=>'Trinidad and Tobago','dial'=>'1','prefix'=>'1'],
        'TN' => ['name'=>'Tunisia','dial'=>'216','prefix'=>''],
        'TR' => ['name'=>'Turkey','dial'=>'90','prefix'=>'0'],
        'TM' => ['name'=>'Turkmenistan','dial'=>'993','prefix'=>'8'],
        'TC' => ['name'=>'Turks and Caicos Islands','dial'=>'1','prefix'=>'1'],
        'TV' => ['name'=>'Tuvalu','dial'=>'688','prefix'=>''],
        'UG' => ['name'=>'Uganda','dial'=>'256','prefix'=>'0'],
        'UA' => ['name'=>'Ukraine','dial'=>'380','prefix'=>'0'],
        'AE' => ['name'=>'UAE','dial'=>'971','prefix'=>'0'],
        'GB' => ['name'=>'Great Britain','dial'=>'44','prefix'=>'0'],
        'US' => ['name'=>'U.S.','dial'=>'1','prefix'=>'1'],
        'UM' => ['name'=>'United States Minor Outlying Islands','dial'=>'','prefix'=>''],
        'UY' => ['name'=>'Uruguay','dial'=>'598','prefix'=>'0'],
        'UZ' => ['name'=>'Uzbekistan','dial'=>'998','prefix'=>''],
        'VU' => ['name'=>'Vanuatu','dial'=>'678','prefix'=>''],
        'VE' => ['name'=>'Venezuela','dial'=>'58','prefix'=>'0'],
        'VN' => ['name'=>'Vietnam','dial'=>'84','prefix'=>'0'],
        'VG' => ['name'=>'Virgin Islands, British','dial'=>'1','prefix'=>'1'],
        'VI' => ['name'=>'Virgin Islands, U.S.','dial'=>'1','prefix'=>'1'],
        'WF' => ['name'=>'Wallis and Futuna','dial'=>'681','prefix'=>''],
        'EH' => ['name'=>'Western Sahara','dial'=>'212','prefix'=>'0'],
        'YE' => ['name'=>'Yemen','dial'=>'967','prefix'=>'0'],
        'ZM' => ['name'=>'Zambia','dial'=>'260','prefix'=>'0'],
        'ZW' => ['name'=>'Zimbabwe','dial'=>'263','prefix'=>'0'],
        'AX' => ['name'=>'Aland Islands','dial'=>'358','prefix'=>'0'],
        'BQ' => ['name'=>'Bonaire, Sint Eustatius and Saba','dial'=>'599','prefix'=>''],
        'CW' => ['name'=>'Curaçao','dial'=>'599','prefix'=>''],
        'GG' => ['name'=>'Guernsey','dial'=>'44','prefix'=>'0'],
        'IM' => ['name'=>'Isle of Man','dial'=>'44','prefix'=>'0'],
        'JE' => ['name'=>'Jersey','dial'=>'44','prefix'=>'0'],
        'ME' => ['name'=>'Montenegro','dial'=>'382','prefix'=>'0'],
        'BL' => ['name'=>'Saint Barthélemy','dial'=>'590','prefix'=>'0'],
        'MF' => ['name'=>'Saint Martin (French part)','dial'=>'590','prefix'=>'0'],
        'RS' => ['name'=>'Serbia','dial'=>'381','prefix'=>'0'],
        'SX' => ['name'=>'Sint Maarten (Dutch part)','dial'=>'1','prefix'=>'1'],
        'SS' => ['name'=>'South Sudan','dial'=>'211','prefix'=>'0'],
    ];
}

function fb_country(string $iso): ?array {
    $countries = fb_country_catalog();
    return $countries[strtoupper(trim($iso))] ?? null;
}
